### ISSUE TITLE
EPIC-004: database 기능 확장 및 구현

### ISSUE THREAD

**Issue by kiku99** [kiku99/plugin-naver-cloud-service-inven-collector#22]

**Comment by skdudddl** [comment]
- [ ] CloudDB 구현
- [ ] Cloud DB for MySQL (VPC)
- [ ] Cloud DB for Redis (VPC)
- [ ] Cloud DB for MongoDB (VPC)
